name: weather_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  sqflite: ^2.1.0+1
  flutter_local_notifications: ^12.0.2
  firebase_messaging: ^13.1.0
  firebase_core: ^1.24.0
  intl: ^0.17.0
  path: ^1.8.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  formz: ^0.4.1
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
